os:
  - linux
  - osx
  - windows

language: node_js
node_js: lts/*

env: HUSKY=0

script: npm run test:coverage
after_success: npx codecov

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      before_script: npm run build
      script: npx semantic-release
      if: branch = master

stages:
  - lint
  - test
  - deploy
